# Generated by Django 3.0.6 on 2020-06-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200601_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='visits',
            new_name='views',
        ),
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
