# Generated by Django 3.0.6 on 2020-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20200611_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
