# Generated by Django 3.0.6 on 2020-06-14 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0004_auto_20200612_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'title')},
        ),
    ]
